/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cccc;

import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author connorarnold
 */
public class AddAppointment extends javax.swing.JPanel {

    /**
     * Creates new form AddAppointment
     */
    public AddAppointment() {
        initComponents();
    }
    
    Connection openConnection;
    EmployeeHome home;
    Integer userId;
    Frame parentFrame;
    Integer userRId;
    public AddAppointment(Connection connection, EmployeeHome eHome, Integer passedUserId, Integer passedRId, Frame passedFrame){
        initComponents();
        parentFrame = passedFrame;
        home = eHome;
        openConnection = connection;
        userId = passedUserId;
        userRId = passedRId;
        errorMessage.setVisible(false);
         try{
            String techQuery = "Call get_region_techs(?)";
            CallableStatement techStmt = openConnection.prepareCall(techQuery);
            techStmt.setInt(1, userRId);
            String techName;
            ResultSet techResultSet = techStmt.executeQuery();
            List<String> techList = new ArrayList<String>();
            techList.add("--None--");
            while (techResultSet.next()){
                techName = techResultSet.getString("e_name");
                techList.add(techName);
            }
            String[] technicianNames = techList.toArray(new String[techList.size()]);
            visibleTechList.setModel(new javax.swing.DefaultComboBoxModel(technicianNames));
            
            String custQuery = "Call regional_customers(?)";
            CallableStatement custStmt = openConnection.prepareCall(custQuery);
            custStmt.setInt(1, userRId);
            String custName;
            ResultSet custResultSet = custStmt.executeQuery();
            List<String> custList = new ArrayList<String>();
            custList.add("--None--");
            while (custResultSet.next()){
                custName = custResultSet.getString("c_name");
                custList.add(custName);
            }
            String[] customerNames = custList.toArray(new String[custList.size()]);
            visibleCustomerList.setModel(new javax.swing.DefaultComboBoxModel(customerNames));
        }
        catch(Exception e)
        {
           throw new IllegalStateException("error",e); 
        }
        
    }
    
    public ResultSet getEmployeeInfo(int eId)
    {
        try{
            String query = "Call get_e_data(" + eId + ")";
            CallableStatement estmt = openConnection.prepareCall(query);
            ResultSet rs2 = estmt.executeQuery();
            ResultSetMetaData metadata = rs2.getMetaData();
            int columnCount = metadata.getColumnCount();    
            while (rs2.next()) {
                String row = "";
                for (int i = 1; i <= columnCount; i++) {
                    row += rs2.getString(i) + ", ";          
                }
            }
            rs2.first();
            return rs2;
        }
        catch(Exception e){
           throw new IllegalStateException("error",e);
        }
    }
    public boolean isNumber(String s)
    {
        for (Integer i = 0; i < s.length(); i++)
            if (!Character.isDigit(s.charAt(i)))
                return false;
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        createAppointment = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        month = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        visibleTechList = new javax.swing.JComboBox<>();
        visibleCustomerList = new javax.swing.JComboBox<>();
        errorMessage = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createAppointment.setText("Create");
        createAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAppointmentActionPerformed(evt);
            }
        });

        jLabel7.setText("Price");

        year.setText("YYYY");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel1.setText("Notes");

        jLabel8.setText("Date");

        price.setText("0");
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        month.setText("MM");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        jLabel2.setText("Technician");

        day.setText("DD");

        jLabel3.setText("Customer");

        jLabel9.setText("/");

        jLabel10.setText("/");

        visibleTechList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        visibleCustomerList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(visibleTechList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(visibleCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel1)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(119, 119, 119)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel9)
                                            .addGap(8, 8, 8)
                                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createAppointment))))
                            .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(errorMessage)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(visibleTechList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(visibleCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createAppointment))
                .addGap(30, 30, 30)
                .addComponent(errorMessage)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        f.setContentPane(home);
        home.setVisible(true);
        f.revalidate();
        f.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAppointmentActionPerformed
        // TODO add your handling code here:
        try{
            if (!isNumber(year.getText()) || year.getText().length() != 4)
                throw new IllegalStateException("Invalid Year");
            if (!isNumber(month.getText()) || month.getText().length() != 2)
                throw new IllegalStateException("Invalid Month");
            if (!isNumber(day.getText()) || day.getText().length() != 2)
                throw new IllegalStateException("Invalid Day");
            if (!isNumber(price.getText()))
                throw new IllegalStateException("Invalid Price");
            String selectedTech = visibleTechList.getSelectedItem().toString();
            String getTechId= "Select e_id From employee where e_name = ?;";
            CallableStatement techIdStmt = openConnection.prepareCall(getTechId);
            techIdStmt.setString(1, selectedTech);
            ResultSet techResultSet= techIdStmt.executeQuery();
            techResultSet.next();
            Integer technicianId = techResultSet.getInt("e_id");
            
            String selectedCust = visibleCustomerList.getSelectedItem().toString();
            String getCustId= "Select c_id From customer where c_name = ?;";
            CallableStatement custIdStmt = openConnection.prepareCall(getCustId);
            custIdStmt.setString(1, selectedCust);
            ResultSet custResultSet= custIdStmt.executeQuery();
            custResultSet.next();
            Integer customerId = custResultSet.getInt("c_id");
            String appointmentDate = year.getText() + "-" + month.getText() + "-" + day.getText();
            Integer appointmentPrice = Integer.parseInt(price.getText());
            String appointmentNotes = notes.getText();
            
            String createAppointmentQuery = "INSERT INTO appointment(e_id, c_id, a_time, a_price, a_notes) VALUES(?,?,?,?,?);";
            CallableStatement createAppointmentStmt = openConnection.prepareCall(createAppointmentQuery);
            createAppointmentStmt.setInt(1,technicianId);
            createAppointmentStmt.setInt(2,customerId);
            createAppointmentStmt.setString(3,appointmentDate);
            createAppointmentStmt.setInt(4,appointmentPrice);
            createAppointmentStmt.setString(5,appointmentNotes);
            createAppointmentStmt.execute();
            
            ResultSet userResultSet = getEmployeeInfo(userId);
            EmployeeHome EHome = new EmployeeHome(userResultSet,openConnection, parentFrame);
            this.setVisible(false);
            javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            f.setContentPane(EHome);
            EHome.setVisible(true);
            f.revalidate();
            f.repaint();
        }
        catch(Exception E){
            String Msg = "" + E;
            String ErrorMsg = Msg.split(":")[1];
            errorMessage.setText(ErrorMsg);
            errorMessage.setVisible(true);
        }
    }//GEN-LAST:event_createAppointmentActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createAppointment;
    private javax.swing.JTextField day;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField month;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> visibleCustomerList;
    private javax.swing.JComboBox<String> visibleTechList;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
