/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cccc;
import java.sql.*;
import java.util.Scanner;
/**
 *
 * @author connorarnold
 */
public class EditEmp extends javax.swing.JPanel {

    /**
     * Creates new form EditEmp
     */
    public EditEmp() {
        initComponents();
    }
    Connection OpenConnection;
    EmployeeHome home;
    ResultSet rs;
    String Username, Password, Email, StreetAddress, City, State, Zip, Phone1, Phone2, Phone3;
    Integer Eid;
    public EditEmp(Connection connection, EmployeeHome ehome, ResultSet ers) {
        initComponents();
        OpenConnection = connection;
        home = ehome;
        rs = ers;
        try{
            rs.first();
            Eid = ers.getInt("e_id");
            Username = rs.getString("e_username");
            Password = rs.getString("e_password");
            Email = rs.getString("e_email");
            StreetAddress = rs.getString("e_street_address");
            City = rs.getString("e_city");
            State = rs.getString("e_state");
            Zip = rs.getString("e_zip");
            if (Zip.length() == 4)
            {
                Zip = "0" + Zip;
            }
            String Phone[] = rs.getString("e_phone").split(" ");
            Phone1 = Phone[0];
            Phone2 = Phone[1];
            Phone3 = Phone[2];
            e_username.setText(Username);
            e_password.setText(Password);
            e_email.setText(Email);
            e_address.setText(StreetAddress);
            e_city.setText(City);
            e_state.setText(State);
            e_zip.setText(Zip);
            e_phone_1.setText(Phone1);
            e_phone_2.setText(Phone2);
            e_phone_3.setText(Phone3);
        }
        catch(Exception e)
        {
           throw new IllegalStateException("error",e); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public ResultSet getEmployeeInfo(int eId)
    {
        try{
            String query = "Call get_e_data(" + eId + ")";
            CallableStatement estmt = OpenConnection.prepareCall(query);
            ResultSet rs2 = estmt.executeQuery();
            ResultSetMetaData metadata = rs2.getMetaData();
            int columnCount = metadata.getColumnCount();    
            while (rs2.next()) {
                String row = "";
                for (int i = 1; i <= columnCount; i++) {
                    row += rs2.getString(i) + ", ";          
                }
            }
            rs2.first();
            return rs2;
        }
        catch(Exception e){
           throw new IllegalStateException("error",e);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTextField jTextField11 = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        e_username = new javax.swing.JTextField();
        e_password = new javax.swing.JTextField();
        e_phone_1 = new javax.swing.JTextField();
        e_email = new javax.swing.JTextField();
        e_address = new javax.swing.JTextField();
        e_city = new javax.swing.JTextField();
        e_state = new javax.swing.JTextField();
        e_zip = new javax.swing.JTextField();
        e_phone_2 = new javax.swing.JTextField();
        e_phone_3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();

        jTextField11.setText("jTextField2");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Phone");

        jLabel5.setText("Email");

        jLabel6.setText("Street Address");

        jLabel7.setText("City");

        jLabel8.setText("State");

        jLabel9.setText("Postal Code");

        e_username.setText("jTextField2");
        e_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_usernameActionPerformed(evt);
            }
        });

        e_password.setText("jTextField2");

        e_phone_1.setText("jTextField2");
        e_phone_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_phone_1ActionPerformed(evt);
            }
        });

        e_email.setText("jTextField2");

        e_address.setText("jTextField2");

        e_city.setText("jTextField2");

        e_state.setText("jTextField2");

        e_zip.setText("jTextField2");

        e_phone_2.setText("jTextField2");

        e_phone_3.setText("jTextField2");

        jLabel1.setText("-");

        jLabel10.setText("-");

        ErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(CancelButton))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(e_phone_1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(2, 2, 2)
                                .addComponent(e_phone_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e_phone_3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(e_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmButton)
                            .addComponent(e_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(ErrorLabel)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(e_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(e_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(e_phone_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(e_phone_2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(e_phone_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(e_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(e_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(e_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(e_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(e_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(ConfirmButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        f.setContentPane(home);
        home.setVisible(true);
        f.revalidate();
        f.repaint();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        // Send the update to mysql
        try{
            String UpdateQuery = "Call update_employee_basic(?,?,?,?,?,?,?,?,?)";
            Username = e_username.getText();
            Password = e_password.getText();
            Email = e_email.getText();
            StreetAddress = e_address.getText();
            City = e_city.getText();
            State = e_state.getText();
            if (State.length() != 2) 
            {
               throw new RuntimeException("State must be 2 characters"); 
            }
            Zip = e_zip.getText();
            int ZipInt = Integer.parseInt(Zip);
            Phone1 = e_phone_1.getText();
            Phone2 = e_phone_2.getText();
            Phone3 = e_phone_3.getText();
            String Phone = Phone1 + " " + Phone2 + " " + Phone3;
            CallableStatement Ustmt = OpenConnection.prepareCall(UpdateQuery);
            Ustmt.setInt(1, Eid);
            Ustmt.setString(2, Username);
            Ustmt.setString(3, Password);
            Ustmt.setString(4, Email);
            Ustmt.setString(5, StreetAddress);
            Ustmt.setString(6, City);
            Ustmt.setString(7, State);
            Ustmt.setInt(8, ZipInt);
            Ustmt.setString(9, Phone);
            Ustmt.executeUpdate();
            
            ResultSet employeeInfo = getEmployeeInfo(Eid);
            EmployeeHome EHome = new EmployeeHome(employeeInfo,OpenConnection);
            this.setVisible(false);
            javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            f.setContentPane(EHome);
            EHome.setVisible(true);
            f.revalidate();
            f.repaint();
        }
        catch(Exception E){
            String Msg = "" + E;
            //String ErrorMsg = Msg.split(":")[1];
            ErrorLabel.setText(Msg);
            ErrorLabel.setVisible(true);
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void e_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_usernameActionPerformed

    private void e_phone_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_phone_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_phone_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextField e_address;
    private javax.swing.JTextField e_city;
    private javax.swing.JTextField e_email;
    private javax.swing.JTextField e_password;
    private javax.swing.JTextField e_phone_1;
    private javax.swing.JTextField e_phone_2;
    private javax.swing.JTextField e_phone_3;
    private javax.swing.JTextField e_state;
    private javax.swing.JTextField e_username;
    private javax.swing.JTextField e_zip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
