/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cccc;

import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author connorarnold
 */
public class EditAppointment extends javax.swing.JPanel {

    /**
     * Creates new form EditAppointment
     */
    public EditAppointment() {
        initComponents();
    }

    Connection openConnection;
    EmployeeHome home;
    ResultSet appointmentResultSet;
    Integer userId;
    Frame parentFrame;
    Integer userRId;
    Integer appointmentId;
    public EditAppointment(Connection passedConnection, EmployeeHome passedHome, ResultSet passedResultSet, int passedUserId, Frame passedFrame, int passedUserRId){
        parentFrame = passedFrame;
        initComponents();
        openConnection = passedConnection;
        home = passedHome;
        appointmentResultSet = passedResultSet;
        userId = passedUserId;
        userRId = passedUserRId;
        errorMessage.setVisible(false);
        try{
            passedResultSet.first();
            appointmentId = passedResultSet.getInt("a_id");
            String streetAddress = passedResultSet.getString("c_street_address");
            String city = passedResultSet.getString("c_city");
            String state = passedResultSet.getString("c_state");
            String zip = passedResultSet.getString("c_zip");
            if (zip.length() == 4)
            {
                zip = "0" + zip;
            }
            String address1 = streetAddress + " " + city + ", " + state + " " + zip;
            address.setText(address1);
            customerName.setText(passedResultSet.getString("c_name"));
            String date[] = passedResultSet.getString("a_time").split("-");
            year.setText(date[0]);
            month.setText(date[1]);
            day.setText(date[2]);
            price.setText(passedResultSet.getString("a_price"));
            notes.setText(passedResultSet.getString("a_notes"));
            String technician = passedResultSet.getString("e_name");
            String techQuery = "Call get_region_techs(?)";
            CallableStatement techStmt = openConnection.prepareCall(techQuery);
            techStmt.setInt(1, userRId);
            ResultSet techResultSet = techStmt.executeQuery();
            List<String> techList = new ArrayList<String>();
            Integer ind,index;
            String techName;
            ind = 0;
            index = 0;
            while (techResultSet.next()){
                techName = techResultSet.getString("e_name");
                techList.add(techName);
                if (techName.equals(technician))
                    ind = index;
                index = index + 1;
            }
            String[] technicianNames = techList.toArray(new String[techList.size()]);
            visibleTechList.setModel(new javax.swing.DefaultComboBoxModel(technicianNames));
            visibleTechList.setSelectedIndex(ind);
        }
        catch(Exception e)
        {
           throw new IllegalStateException("error",e); 
        }
    }
    
    public ResultSet getEmployeeInfo(int eId)
    {
        try{
            String query = "Call get_e_data(" + eId + ")";
            CallableStatement estmt = openConnection.prepareCall(query);
            ResultSet rs2 = estmt.executeQuery();
            ResultSetMetaData metadata = rs2.getMetaData();
            int columnCount = metadata.getColumnCount();    
            while (rs2.next()) {
                String row = "";
                for (int i = 1; i <= columnCount; i++) {
                    row += rs2.getString(i) + ", ";          
                }
            }
            rs2.first();
            return rs2;
        }
        catch(Exception e){
           throw new IllegalStateException("error",e);
        }
    }
    
    public boolean isNumber(String s)
    {
        for (Integer i = 0; i < s.length(); i++)
            if (!Character.isDigit(s.charAt(i)))
                return false;
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        visibleTechList = new javax.swing.JComboBox<>();
        customerName = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Notes");

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        jLabel2.setText("Technician");

        jLabel3.setText("Customer");

        jLabel4.setText("Address");

        visibleTechList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        customerName.setText("jLabel5");

        address.setText("jLabel6");

        jLabel7.setText("Price");

        year.setText("YYYY");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel8.setText("Date");

        price.setText("jTextField2");

        month.setText("MM");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        day.setText("DD");

        jLabel9.setText("/");

        jLabel10.setText("/");

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerName)
                                    .addComponent(visibleTechList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel9)
                                        .addGap(8, 8, 8)
                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 129, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessage)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(visibleTechList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(updateButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessage)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            String deleteAppointmentQuery  = "Delete FROM appointment WHERE a_id = ?";
            CallableStatement deleteAppointmentStatement = openConnection.prepareCall(deleteAppointmentQuery);
            deleteAppointmentStatement.setInt(1, appointmentId);
            deleteAppointmentStatement.execute();

            ResultSet managerResultSet = getEmployeeInfo(userId);
            EmployeeHome EHome = new EmployeeHome(managerResultSet,openConnection, parentFrame);
            this.setVisible(false);
            javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            f.setContentPane(EHome);
            EHome.setVisible(true);
            f.revalidate();
            f.repaint();
        }
        catch(Exception e){
           throw new IllegalStateException("error",e);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        f.setContentPane(home);
        home.setVisible(true);
        f.revalidate();
        f.repaint();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try{
            if (!isNumber(year.getText()) || year.getText().length() != 4)
                throw new IllegalStateException("Invalid Year");
            if (!isNumber(month.getText()) || month.getText().length() != 2)
                throw new IllegalStateException("Invalid Month");
            if (!isNumber(day.getText()) || day.getText().length() != 2)
                throw new IllegalStateException("Invalid Day");
            if (!isNumber(price.getText()))
                throw new IllegalStateException("Invalid Price");
            String selectedTech = visibleTechList.getSelectedItem().toString();
            String getTechId= "Select e_id From employee where e_name = ?;";
            CallableStatement techIdStmt = openConnection.prepareCall(getTechId);
            techIdStmt.setString(1, selectedTech);
            ResultSet techResultSet= techIdStmt.executeQuery();
            techResultSet.next();
            Integer technicianId = techResultSet.getInt("e_id");
            
            String newDate = year.getText() + "-" + month.getText() + "-" + day.getText();
            
            String updateQuery = "Call update_appointment(?,?,?,?,?)";
            CallableStatement updateStmt = openConnection.prepareCall(updateQuery);
            updateStmt.setInt(1, appointmentId);
            updateStmt.setInt(2,technicianId);
            updateStmt.setString(3, newDate);
            updateStmt.setInt(4,Integer.parseInt(price.getText()));
            updateStmt.setString(5,notes.getText());
            updateStmt.execute();
            ResultSet userResultSet = getEmployeeInfo(userId);
            EmployeeHome EHome = new EmployeeHome(userResultSet,openConnection, parentFrame);
            this.setVisible(false);
            javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            f.setContentPane(EHome);
            EHome.setVisible(true);
            f.revalidate();
            f.repaint();
        }
        catch(Exception E){
            String Msg = "" + E;
            String ErrorMsg = Msg.split(":")[1];
            errorMessage.setText(ErrorMsg);
            errorMessage.setVisible(true);
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel customerName;
    private javax.swing.JTextField day;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField price;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> visibleTechList;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
