/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cccc;
import java.sql.*;
import java.util.*;


/**
 *
 * @author connorarnold
 */

public class EmployeeHome extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeHome
     */
    public EmployeeHome() {
        initComponents();
    }
    String id;
    Connection openconnection;
    ResultSet ers;
    public EmployeeHome(ResultSet rs, Connection connection) {
        initComponents();
        try
        {
            id = rs.getString("e_id");
            eName.setText(rs.getString("e_name"));
            int rId = rs.getInt("r_id");
            System.out.println(rId);
            openconnection = connection;
            String eQuery = "Select r_id_to_name(?) as r_name";
            CallableStatement eStmt = openconnection.prepareCall(eQuery);
            eStmt.setInt(1, rId);
            ResultSet eRs = eStmt.executeQuery();
            eRs.first();
            eBranch.setText(eRs.getString("r_name"));
            ePosition.setText(rs.getString("e_role"));
            eSalary.setText(rs.getString("e_salary"));
            eStartDate.setText(rs.getString("e_start_date"));
            ePhone.setText(rs.getString("e_phone"));
            eEmail.setText(rs.getString("e_email"));
            String Zip = rs.getString("e_zip");
            if (Zip.length() == 4)
            {
                Zip = "0" + Zip;
            }
            String address = rs.getString("e_street_address") + "\n" + 
                    rs.getString("e_city") + ", " + rs.getString("e_state") + " " +
                    Zip;

            eAddress.setText(address);
            ers = rs;

            //Set up the employees tab
            if (!ePosition.getText().equals("Manager"))
            {
                Tab2.remove(EmployeesTab);
            }
            else
            {
                List<String> EmpList = new ArrayList<String>();
                String REQuery = "Select e_name from employee where r_id = ?";
                CallableStatement RE = openconnection.prepareCall(REQuery);
                RE.setInt(1, rId);
                ResultSet RERS = RE.executeQuery();
                String EmpName;
                while (RERS.next()){
                    System.out.println(EmployeesTab.getSelectedValuesList());
                    EmpName = RERS.getString("e_name");
                    EmpList.add(EmpName);
                }
                String[] RegionEmployees = EmpList.toArray(new String[EmpList.size()]);
                EmployeesTab.setListData(RegionEmployees);         
            }
        
        }
        catch(Exception e)
        {
           throw new IllegalStateException("error",e); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Tab2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eName = new javax.swing.JLabel();
        eBranch = new javax.swing.JLabel();
        ePosition = new javax.swing.JLabel();
        eSalary = new javax.swing.JLabel();
        eStartDate = new javax.swing.JLabel();
        ePhone = new javax.swing.JLabel();
        eEmail = new javax.swing.JLabel();
        eAddress = new javax.swing.JLabel();
        UpdateInfoButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeesTab = new javax.swing.JList<>();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jLabel1.setText("Name");

        jLabel2.setText("Branch");

        jLabel3.setText("Position");

        jLabel4.setText("Salary");

        jLabel5.setText("Start Date");

        jLabel6.setText("Phone");

        jLabel7.setText("Email");

        jLabel8.setText("Address");

        eName.setText("eName");

        eBranch.setText("eBranch");

        ePosition.setText("ePosition");

        eSalary.setText("eSalary");

        eStartDate.setText("eStartDate");

        ePhone.setText("ePhone");

        eEmail.setText("eEmail");

        eAddress.setText("eAddress");

        UpdateInfoButton.setBackground(new java.awt.Color(51, 51, 255));
        UpdateInfoButton.setLabel("Update Info");
        UpdateInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eAddress)
                            .addComponent(eEmail)
                            .addComponent(ePhone)
                            .addComponent(eStartDate)
                            .addComponent(eName)
                            .addComponent(eBranch)
                            .addComponent(eSalary)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ePosition))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UpdateInfoButton)
                        .addGap(7, 7, 7)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eBranch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ePosition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ePhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(eEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(eAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateInfoButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Tab2.addTab("Home", jPanel1);

        EmployeesTab.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        EmployeesTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeNameClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeesTab);

        Tab2.addTab("Employees", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoButtonActionPerformed
        // TODO add your handling code here:
        try{
            EditEmp emp = new EditEmp(openconnection,this,ers);
            javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            f.setContentPane(emp);
            emp.setVisible(true);
            f.repaint();
            f.revalidate();

        }
        catch(Exception e){
            throw new IllegalStateException("error",e);
        }
    }//GEN-LAST:event_UpdateInfoButtonActionPerformed

    private void EmployeeNameClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeNameClicked
        // TODO add your handling code here:
        try{
            javax.swing.JList list = (javax.swing.JList)evt.getSource();
            if (evt.getClickCount() == 2) 
            {
                String Mquery = "Select * from employee where e_name = ?";
                CallableStatement Mestmt = openconnection.prepareCall(Mquery);
                String SelectedEmployee = EmployeesTab.getSelectedValuesList().get(0);
                Mestmt.setString(1,SelectedEmployee);
                ResultSet Mers = Mestmt.executeQuery();
                ManagerEditEmp Memp = new ManagerEditEmp(openconnection,this,Mers);
                javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                f.setContentPane(Memp);
                Memp.setVisible(true);
                f.repaint();
                f.revalidate();
            }
        }
        catch(Exception e){
            throw new IllegalStateException("error",e);
        }
    }//GEN-LAST:event_EmployeeNameClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> EmployeesTab;
    private javax.swing.JTabbedPane Tab2;
    private javax.swing.JButton UpdateInfoButton;
    private javax.swing.JLabel eAddress;
    private javax.swing.JLabel eBranch;
    private javax.swing.JLabel eEmail;
    private javax.swing.JLabel eName;
    private javax.swing.JLabel ePhone;
    private javax.swing.JLabel ePosition;
    private javax.swing.JLabel eSalary;
    private javax.swing.JLabel eStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
