/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cccc;
import java.sql.*;
import java.util.*;
/**
 *
 * @author connorarnold
 */
public class ManagerEditEmp extends javax.swing.JPanel {

    /**
     * Creates new form ManagerEditEmp
     */
    public ManagerEditEmp() {
        initComponents();
    }
    Connection OpenConnection;
    EmployeeHome home;
    ResultSet rs;
    Integer Mid;
    String Username, Name, Salary, Start, Position, Password, Email, StreetAddress, City, State, Zip, Phone1, Phone2, Phone3,  Eid;
    public ManagerEditEmp(Connection connection, EmployeeHome ehome, ResultSet ers, int ManagerId) 
    {
        initComponents();
        OpenConnection = connection;
        home = ehome;
        rs = ers;
        Mid = ManagerId;
        try{
            rs.first();
            Eid = ers.getString("e_id");
            Name = ers.getString("e_name");
            Position = ers.getString("e_role");
            Start = ers.getString("e_start_date");
            Salary = ers.getString("e_salary");
            Username = rs.getString("e_username");
            Password = rs.getString("e_password");
            Email = rs.getString("e_email");
            StreetAddress = rs.getString("e_street_address");
            City = rs.getString("e_city");
            State = rs.getString("e_state");
            Zip = rs.getString("e_zip");
            if (Zip.length() == 4)
            {
                Zip = "0" + Zip;
            }
            String Address = rs.getString("e_street_address") + "\n" + 
                    rs.getString("e_city") + ", " + rs.getString("e_state") + " " +
                    Zip;

            String Phone = rs.getString("e_phone");
            
            //Make the dropdowns for regions
            int rId = rs.getInt("r_id");
            System.out.println(rId);
            String eQuery = "Select r_id_to_name(?) as r_name";
            CallableStatement eStmt = OpenConnection.prepareCall(eQuery);
            eStmt.setInt(1, rId);
            ResultSet eRs = eStmt.executeQuery();
            eRs.first();
            String RQuery = "Select r_name From region";
            CallableStatement RStmt = OpenConnection.prepareCall(RQuery);
            ResultSet RRS = RStmt.executeQuery();
            List<String> RegionList = new ArrayList<String>();
            String RegionName;
            Integer ind,index;
            ind = 0;
            index = 0;
            while (RRS.next()){
                RegionName = RRS.getString("r_name");
                RegionList.add(RegionName);
                if (eRs.getString("r_name").equals(RegionName))
                    ind = index;
                index = index + 1;
            }
            String[] RegionNames = RegionList.toArray(new String[RegionList.size()]);
            regions.setModel(new javax.swing.DefaultComboBoxModel(RegionNames));
            regions.setSelectedIndex(ind);
                    
            //e_branch.setText(eRs.getString("r_name"));
            e_id.setText(Eid);
            e_name.setText(Name);
            e_title.setText(Position);
            e_salary.setText(Salary);
            e_start.setText(Start);
            e_username.setText(Username);
            e_password.setText(Password);
            e_email.setText(Email);
            e_address.setText(Address);
            e_phone.setText(Phone);
        }
        catch(Exception e)
        {
           throw new IllegalStateException("error",e); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public ResultSet getEmployeeInfo(int eId)
    {
        try{
            String query = "Call get_e_data(" + eId + ")";
            CallableStatement estmt = OpenConnection.prepareCall(query);
            ResultSet rs2 = estmt.executeQuery();
            ResultSetMetaData metadata = rs2.getMetaData();
            int columnCount = metadata.getColumnCount();    
            while (rs2.next()) {
                String row = "";
                for (int i = 1; i <= columnCount; i++) {
                    row += rs2.getString(i) + ", ";          
                }
            }
            rs2.first();
            return rs2;
        }
        catch(Exception e){
           throw new IllegalStateException("error",e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        e_title = new javax.swing.JTextField();
        e_salary = new javax.swing.JTextField();
        e_username = new javax.swing.JTextField();
        e_password = new javax.swing.JTextField();
        e_address = new javax.swing.JLabel();
        e_email = new javax.swing.JLabel();
        e_phone = new javax.swing.JLabel();
        e_id = new javax.swing.JLabel();
        e_start = new javax.swing.JLabel();
        e_name = new javax.swing.JLabel();
        regions = new javax.swing.JComboBox<>();

        jLabel1.setText("Employee ID");

        jLabel2.setText("Employee Name");

        jLabel3.setText("Employee Branch");

        jLabel4.setText("Employee Position");

        jLabel5.setText("Employee Salary");

        jLabel6.setText("Employee Start Date");

        jLabel7.setText("Employee Username");

        jLabel8.setText("Employee Password");

        jLabel9.setText("Employee Phone");

        jLabel10.setText("Employee Email");

        jLabel11.setText("Employee Address");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        e_title.setText("jTextField4");
        e_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_titleActionPerformed(evt);
            }
        });

        e_salary.setText("jTextField5");
        e_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_salaryActionPerformed(evt);
            }
        });

        e_username.setText("jTextField7");

        e_password.setText("jTextField8");
        e_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_passwordActionPerformed(evt);
            }
        });

        e_address.setText("jLabel12");

        e_email.setText("jLabel12");

        e_phone.setText("jLabel12");

        e_id.setText("jLabel12");

        e_start.setText("jLabel12");

        e_name.setText("jLabel12");

        regions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        regions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e_email)
                                    .addComponent(e_phone)
                                    .addComponent(e_address)
                                    .addComponent(jButton3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_start)
                            .addComponent(e_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_name)
                            .addComponent(e_id)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(e_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(e_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(e_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(e_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(e_start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(e_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(e_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(e_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(e_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(e_address))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        String SelectedRegionName = regions.getSelectedItem().toString();
        String GetRid= "Select r_id From region where r_name = ?;";
        CallableStatement RegionId = OpenConnection.prepareCall(GetRid);
        RegionId.setString(1, SelectedRegionName);
        ResultSet RidRs= RegionId.executeQuery();
        RidRs.next();
        Integer e_r_id = RidRs.getInt("r_id");
        
        String UpdateEmployee = "Call update_employee_manager(?,?,?,?,?,?);";
        CallableStatement UpdateE = OpenConnection.prepareCall(UpdateEmployee);
        UpdateE.setInt(1, Integer.parseInt(Eid));
        UpdateE.setInt(2, e_r_id);
        UpdateE.setString(3, e_title.getText());
        UpdateE.setInt(4, Integer.parseInt(e_salary.getText()));
        UpdateE.setString(5, e_username.getText());
        UpdateE.setString(6, e_password.getText());
        UpdateE.executeUpdate();
        
        ResultSet employeeInfo = getEmployeeInfo(Mid);
            EmployeeHome EHome = new EmployeeHome(employeeInfo,OpenConnection);
            this.setVisible(false);
            javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            f.setContentPane(EHome);
            EHome.setVisible(true);
            f.revalidate();
            f.repaint();
        }
        catch(Exception e)
        {
           throw new IllegalStateException("error",e); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.JFrame f = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        f.setContentPane(home);
        home.setVisible(true);
        f.revalidate();
        f.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void e_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_titleActionPerformed

    private void e_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_salaryActionPerformed

    private void e_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_passwordActionPerformed

    private void regionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel e_address;
    private javax.swing.JLabel e_email;
    private javax.swing.JLabel e_id;
    private javax.swing.JLabel e_name;
    private javax.swing.JTextField e_password;
    private javax.swing.JLabel e_phone;
    private javax.swing.JTextField e_salary;
    private javax.swing.JLabel e_start;
    private javax.swing.JTextField e_title;
    private javax.swing.JTextField e_username;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> regions;
    // End of variables declaration//GEN-END:variables
}
